-- SQL Schema for TECHLOG Blog (Supabase / PostgreSQL)

-- 1. Drop existing tables and triggers if they exist
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
DROP FUNCTION IF EXISTS public.handle_new_user;
DROP TABLE IF EXISTS public.articles;
DROP TABLE IF EXISTS public.users;

-- 2. Create users table (linked to Supabase Auth)
CREATE TABLE public.users (
    id UUID PRIMARY KEY REFERENCES auth.users (id) ON DELETE CASCADE,
    email TEXT UNIQUE NOT NULL,
    role TEXT NOT NULL DEFAULT 'Reader',
    nickname TEXT,
    fullname TEXT,
    phone TEXT,
    photo_url TEXT,
    bio TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 3. Create articles table
CREATE TABLE public.articles (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    summary TEXT NOT NULL,
    category TEXT NOT NULL,
    author_id UUID NOT NULL REFERENCES public.users (id) ON DELETE CASCADE,
    image_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 4. Enable Row Level Security (RLS) and define public policies
-- We allow full public access (all operations) using the anon key for simplicity
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.articles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public access users" ON public.users FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access articles" ON public.articles FOR ALL USING (true) WITH CHECK (true);

-- 5. Create trigger to automatically insert profile in public.users on signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.users (id, email, role, nickname)
  VALUES (
    new.id,
    new.email,
    CASE 
      WHEN new.email = 'dariponcee@gmail.com' THEN 'Admin'
      ELSE COALESCE(new.raw_user_meta_data->>'role', 'Reader')
    END,
    COALESCE(new.raw_user_meta_data->>'nickname', split_part(new.email, '@', 1))
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- 6. Insert default admin user into auth.users (password: AdminPass123!)
-- Enable pgcrypto extension if not already enabled
CREATE EXTENSION IF NOT EXISTS pgcrypto;

INSERT INTO auth.users (
    instance_id,
    id,
    aud,
    role,
    email,
    encrypted_password,
    email_confirmed_at,
    raw_app_meta_data,
    raw_user_meta_data,
    created_at,
    updated_at,
    confirmation_token,
    email_change,
    email_change_token_new,
    recovery_token
) VALUES (
    '00000000-0000-0000-0000-000000000000',
    'd0000000-0000-0000-0000-000000000001', -- Fixed UUID for admin
    'authenticated',
    'authenticated',
    'admin@techblog.com',
    crypt('AdminPass123!', gen_salt('bf')),
    NOW(),
    '{"provider":"email","providers":["email"]}',
    '{"role":"Admin","nickname":"Admin"}', -- Metadata read by trigger
    NOW(),
    NOW(),
    '',
    '',
    '',
    ''
) ON CONFLICT (id) DO NOTHING;

-- Force update in public.users to ensure role is Admin
INSERT INTO public.users (id, email, role, nickname, fullname)
VALUES (
    'd0000000-0000-0000-0000-000000000001',
    'admin@techblog.com',
    'Admin',
    'Admin',
    'Administrador TECHLOG'
) ON CONFLICT (id) DO UPDATE 
SET role = 'Admin', nickname = 'Admin', fullname = 'Administrador TECHLOG';

-- 7. Insert default articles
INSERT INTO public.articles (id, title, summary, category, content, image_url, author_id, created_at)
VALUES 
(
    1,
    'El impacto de GPT-5 en la industria del software',
    'Analizamos cómo el próximo modelo lingüístico de OpenAI promete redefinir el rol de los ingenieros de software y la automatización de código.',
    'IA',
    '## Introducción

El desarrollo de la Inteligencia Artificial está avanzando a pasos agigantados. Con la inminente llegada de GPT-5, el ecosistema del desarrollo de software se encuentra al borde de una transformación sin precedentes.

## ¿Qué podemos esperar?

* **Generación de código multi-archivo**: Capacidad de diseñar arquitecturas completas desde un prompt.
* **Razonamiento avanzado**: Menos alucinaciones y mayor comprensión del contexto del negocio.
* **Agentes autónomos**: Sistemas capaces de depurar, probar y desplegar software sin intervención humana constante.

> "La IA no reemplazará a los programadores, pero los programadores que usan IA reemplazarán a los que no la usan."

## Conclusión

Adaptarse a estas nuevas herramientas es fundamental para seguir siendo relevantes en una industria hiper-competitiva.',
    'https://images.unsplash.com/photo-1677442136019-21780efad99a?q=80&w=600&auto=format&fit=crop',
    'd0000000-0000-0000-0000-000000000001',
    NOW() - INTERVAL '1 day'
),
(
    2,
    'Por qué Rust es el futuro del desarrollo de sistemas',
    'Un repaso profundo de la seguridad de memoria, rendimiento crudo y concurrencia sin miedos que ofrece el lenguaje favorito de los desarrolladores.',
    'Software',
    '## Seguridad sin Recolector de Basura

Rust ha ganado popularidad gracias a su enfoque innovador en la gestión de memoria. A diferencia de lenguajes como Java o Go, Rust no tiene un recolector de basura (garbage collector). En su lugar, utiliza un sistema de **propiedad (ownership)** y préstamo de variables que el compilador valida en tiempo de compilación.

## Ventajas Clave:

1. **Rendimiento crudo**: Equivalente a C y C++.
2. **Seguridad de memoria garantizada**: Previene errores comunes como desbordamientos de buffer o referencias nulas.
3. **Excelente soporte para concurrencia**: Elimina las condiciones de carrera de datos.

## Conclusión

Grandes tecnológicas como Microsoft, Google y AWS están reescribiendo componentes críticos de su infraestructura en Rust. Es hora de prestarle atención.',
    'https://images.unsplash.com/photo-1555066931-4365d14bab8c?q=80&w=600&auto=format&fit=crop',
    'd0000000-0000-0000-0000-000000000001',
    NOW() - INTERVAL '2 days'
),
(
    3,
    'La revolución de los procesadores cuánticos',
    'Exploramos los hitos más recientes en computación cuántica y cómo amenazan la criptografía moderna en el corto plazo.',
    'Hardware',
    '## La carrera por los Qubits

La computación tradicional se basa en bits (0 o 1). La computación cuántica, en cambio, utiliza qubits que aprovechan los principios de superposición y entrelazamiento. Esto permite procesar volúmenes masivos de información de forma paralela.

## Desafíos actuales:

* **Decoherencia cuántica**: Mantener los qubits estables requiere temperaturas cercanas al cero absoluto (-273°C).
* **Corrección de errores**: Se necesitan miles de qubits físicos para crear un solo qubit lógico corregido.

## Impacto en la Criptografía

Los algoritmos cuánticos como el de Shor son capaces de romper los sistemas criptográficos de clave pública más comunes (RSA y ECC). La transición hacia la **criptografía post-cuántica** ya ha comenzado.',
    'https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=600&auto=format&fit=crop',
    'd0000000-0000-0000-0000-000000000001',
    NOW() - INTERVAL '3 days'
),
(
    4,
    'Cómo proteger tus aplicaciones contra inyecciones SQL',
    'Guía práctica con ejemplos reales para blindar tus bases de datos contra una de las vulnerabilidades más antiguas y destructivas de la web.',
    'Ciberseguridad',
    '## ¿Qué es la Inyección SQL?

La inyección SQL (SQLi) ocurre cuando un atacante logra insertar código SQL malicioso dentro de una consulta realizada por la aplicación a la base de datos. Esto puede resultar en la filtración de contraseñas, robo de datos o incluso destrucción de la base de datos.

## Medidas preventivas:

1. **Usar siempre Parametrización**: Nunca concatenar strings en queries.
2. **Validación de entradas**: Filtrar caracteres sospechosos.
3. **Principio de menor privilegio**: Que la conexión de la app solo tenga los permisos estrictamente necesarios.',
    'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=600&auto=format&fit=crop',
    'd0000000-0000-0000-0000-000000000001',
    NOW() - INTERVAL '4 days'
)
ON CONFLICT (id) DO NOTHING;

-- Adjust sequence if needed
SELECT setval(pg_get_serial_sequence('public.articles', 'id'), COALESCE(MAX(id), 1)) FROM public.articles;
